version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - .:/react_typescript_taskmania
    container_name: react_typescript_taskmania-c
    image: react_typescript_taskmania-img
    ports:
      - 3000:3000
    command: npm start
    environment:
      - WACTHPACK_POLLING=true
